site_name: pyds9plugin doc
site_url: https://vpicouet.github.io/pyds9plugin-doc/
theme:
  name: readthedocs
markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - toc:
      baselevel: 0
      toc_depth: "1-4"
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
    - Home: 'index.md'
    - 'User Guide':
        - 'Installation': 'install.md'
        - 'Tutorials': 'user.md'
        - 'Important features': 'feature.md'
        - 'All the functions': 'function.md'
        - 'Videos':
            - 'Multi-image processing': 'videos_multi.md'
            - 'Instrumentation': 'videos_instru.md'
            - 'Software': 'videos_soft.md'
            - 'Generic': 'videos_generic.md'
        # - 'Styling your docs': 'styling-your-docs.md'
    - About:
        - 'Development philosophy': 'philosophy.md'
        - 'Concept and implementation': 'concept.md'
        - 'License': 'license.md'
# plugins:
#   - search
#   - bibtex:
#       bib_file: "refs.bib"
#       cite_style: "pandoc"
